services:
  - type: web
    name: redsocial
    env: php
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "php -S 0.0.0.0:10000 -t public"
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        value: tu-clave-secreta
      - key: DATABASE_URL
        value: sqlite:///%kernel.project_dir%/var/data.db
